/*Owner & Copyrights: Vance King Saxbe. A.*/<ul>
<li><a href="http://www.scriptol.com/programming/graphic-algorithms.php">Amazing algorithms to enhance or transform images</a> <span class="rssdate">Wed, 16 Nov 2011 07:22:15 GMT</span><br><span class='rssdesc'>List of algorithms for image processing whose level of intelligence avoids infinitely complex tasks.</span></li>
<li><a href="http://www.scriptol.com/design/gimp/logo.php">From sketch to logo: Creating a text and image logo with GIMP</a> <span class="rssdate">Wed, 16 Nov 2011 07:21:42 GMT</span><br><span class='rssdesc'>Alpha to logo adds a texture to images with some fancy effects.</span></li>
<li><a href="http://www.scriptol.com/software/windows-8.php">Windows 8, fake welcome screen, true 1st april fool</a> <span class="rssdate">Fri, 15 Apr 2011 08:00:20 UTC</span><br><span class='rssdesc'>Windows 8 will be different. The information filter slowly on this new system that will address all types of machines: tablets, netbooks, desktops. Test versions were submitted to some manufacturers computer for they test it on their hardware.</span></li>
<li><a href="http://www.scriptol.com/software/internet-explorer-10.php">Internet Explorer 10</a> <span class="rssdate">Fri, 15 Apr 2011 07:55:29 UTC</span><br><span class='rssdesc'>With Internet Explorer 10, Microsoft wants to develop further support for HTML 5 and CSS 3. A trial version is already available. The shadows are now supported to create widgets similar to the native components of mobile phone systems.</span></li>
<li><a href="http://www.scriptol.com/web/search-engine-future.php">Future of search engines</a> <span class="rssdate">Thu, 07 Apr 11 04:01:19 -0500</span><br><span class='rssdesc'>For Stefan Weitz, who is leading Bing search engine:<em></span></li>
<li><a href="http://www.scriptol.com/technologies/kinect.php">Kinect, a door on virtual reality</a> <span class="rssdate">Sat, 02 Apr 11 12:06:07 -0500</span><br><span class='rssdesc'>He currently works on XBox 360 with a expansion box and should in future be integrated into Windows.As noted in the article on new interfaces to computers, there are many different systems to interact with a computer and be integrated into a virtual world</span></li>
<li><a href="http://www.scriptol.com/technologies/future-computer.php">The computer of tomorrow</a> <span class="rssdate">Sat, 02 Apr 11 12:05:57 -0500</span><br><span class='rssdesc'>You already hold it in the hand, its power will multiply and placed in a dock, it can connect to all devices.For most users, especially those of the Internet, the increasing power of mobile units is becoming sufficient to render the PC useless</span></li>
<li><a href="http://www.scriptol.com/web-programming.php">The Scriptol PHP compiler</a> <span class="rssdate">Fri, 21 Sep 2007 15:20:35 GMT</span><br><span class='rssdesc'>Free compiler for building PHP applications for the Web or the desktop. The program compile a scriptol source either to PHP or to binary executable. Work even inside Web pages. GPL license.</span></li>
<li><a href="http://www.scriptol.com/scripts/php-ftp-synchronizer.php">PHP FTP Synchronizer</a> <span class="rssdate">Fri, 21 Sep 2007 15:03:57 GMT</span><br><span class='rssdesc'>Free program to update your website from local files. PHP FTP Synchronizer traverses the tree structure of the source directory recursively and updates the file on the website, by replacing newly created pages or modified files. Several options for best speed. </span></li>
<li><a href="http://www.scriptol.com/rss/ara.php">The Ara RSS feed editor</a> <span class="rssdate">Fri, 21 Sep 2007 15:14:04 GMT</span><br><span class='rssdesc'>Extract an RSS feed in the RSS 2.0 or 1.0 format and display the content.</span></li>
<li><a href="http://www.scriptol.com/ajax/frameworks.php">List and comparison of Ajax PHP frameworks</a> <span class="rssdate">Fri, 21 Sep 2007 15:21:26 GMT</span><br><span class='rssdesc'>These libraries are comprised of a JavaScript part for the browser side, and PHP scripts working on the server. A small library with a single PHP class and JavaScript code. </span></li>
</ul>

/*email to provide support at vancekingsaxbe@powerdominionenterprise.com, businessaffairs@powerdominionenterprise.com, For donations please write to fundraising@powerdominionenterprise.com*/